language: python
python:
  - "2.7"
install:
  - pip install $DJANGO --use-mirrors
  - make travis
env:
  - DJANGO="django==1.5"
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  on_success: "never"
